### ISSUE TITLE
Package conflict on LogisticRegression tutorial

### ISSUE THREAD

**Issue by arolihas** [TuringLang/TuringTutorials#69]
Question on: https://turing.ml/dev/tutorials/2-logisticregression/

When I try to follow along on this guide in my own notebook, there are some package management issues. When loading the RDataset, there is an identifier not found error, which was resolved by using the RData#master package as recommended [here](https://discourse.julialang.org/t/rdata-undefvarerror-identifier-not-defined/39276). 

I can download the dataset now, but the MLDataUtils package is now incompatible. When I try to add it, I get this error due to some conflict with required versions of DataFrames packages:
````ERROR: Unsatisfiable requirements detected for package MLDataUtils [cc2ba9b6]:
 MLDataUtils [cc2ba9b6] log:

 ├─possible versions are: [0.4.0, 0.5.0-0.5.1] or uninstalled

 ├─restricted to versions * by an explicit requirement, leaving only versions [0.4.0, 0.5.0-0.5.1]

 └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: uninstalled — no versions left

   └─DataFrames [a93c6f00] log:

     ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.1] or uninstalled

     └─restricted to versions 0.21 by RData [df47a6cb], leaving only versions 0.21.0-0.21.1

       └─RData [df47a6cb] log:

         ├─possible versions are: 0.7.2 or uninstalled

         └─RData [df47a6cb] is fixed to version 0.7.2
````

**Comment by cpfiffer** [comment]
Thanks for the issue, but the point I was trying to make [here](https://github.com/TuringLang/TuringTutorials/issues/69) is that this has nothing to do with us -- it's not something we can fix. There is no benefit to having an issue here for something that is largely out of our control. 

If you want the tutorials to work, you can go back down to RData 0.7 or use the Julia evironment defined by the [Manifest](https://github.com/TuringLang/TuringTutorials/blob/master/Manifest.toml) and [Project](https://github.com/TuringLang/TuringTutorials/blob/master/Project.toml) files in the TuringTutorials repo. These should function without issue, since it's the environment that rendered the tutorials.

**Comment by arolihas** [comment]
Okay thanks.
